spring.application.name=gini
spring.jpa.open-in-view=false
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# server.error.include-stacktrace=never - versão antiga
spring.web.error.include-stacktrace= never

# gera o create.sql automaticamente
# spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
# spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.hibernate.hbm2ddl.delimiter=; 
# spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql


#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true