# server.error.include-stacktrace=never - versão antiga
spring.web.error.include-stacktrace= never

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=false

spring.flyway.enabled=false

api.security.token.secret =${JWT_SECRET}

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false