spring.application.name=horario
spring.profiles.active=test

spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.security.jwt-secret=CHANGEME_DEV_ONLY_SECRET_32_CHARS_MINIMUM_XYZ
app.security.jwt-expiration-ms=3600000
app.security.debug-role-enabled=false
