# server.error.include-stacktrace=never - versão antiga
spring.web.error.include-stacktrace= never

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gini}
spring.datasource.username=${DB_USER:gini}
spring.datasource.password=${DB_PASSWORD:gini}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=false

spring.flyway.enabled=false

api.security.token.secret =${JWT_SECRET:gini}

spring.jpa.hibernate.ddl-auto=update