# server.error.include-stacktrace=never - versão antiga
spring.web.error.include-stacktrace= never

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=false

spring.flyway.enabled=false

api.security.token.secret =${JWT_SECRET:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmYXRlYy1naW5pIiwic3ViIjoidGVzdGVAdGVzdGUuY29tIiwiZXhwIjoxNzgwNzgyMjUzfQ.OIiYKgbDpRIgM6lHwaEIO2F8gvDGLgPKTmXDhtsBK8o}

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false