create table password_reset_token (
    id_password_reset_token bigint generated by default as identity,
    id_usuario bigint not null,
    token_hash varchar(64) not null unique,
    expires_at timestamp(6) with time zone not null,
    used boolean not null default false,
    created_at timestamp(6) with time zone not null,
    used_at timestamp(6) with time zone,
    primary key (id_password_reset_token)
);

alter table if exists password_reset_token
    add constraint FK_password_reset_token_usuario
    foreign key (id_usuario) references usuario;

create index IX_password_reset_token_usuario_used
    on password_reset_token (id_usuario, used);