CREATE TABLE curso (
    id_curso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    periodicidade VARCHAR(255) NOT NULL,
    duracao INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO')),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tipo_sala (
    id_tipo_sala BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tipo_recurso (
    id_tipo_recurso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professor (
    id_professor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cidade VARCHAR(255),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO')),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bloco_horario (
    id_bloco_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duracao INTEGER NOT NULL,
    hora_inicio TIME(0) NOT NULL,
    hora_fim TIME(0) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE periodo_atividade_quadro (
    id_periodo_atividade_quadro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER,
    periodo INTEGER,
    data_inicio DATE,
    data_fim DATE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO')),
    tipo_periodo_atividade_quadro SMALLINT CHECK (tipo_periodo_atividade_quadro BETWEEN 0 AND 2),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sala (
    id_sala BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    capacidade INTEGER NOT NULL,
    id_tipo_sala BIGINT NOT NULL REFERENCES tipo_sala(id_tipo_sala),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE disciplina (
    id_disciplina BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    carga_horaria INTEGER,
    tipo_disciplina VARCHAR(255) NOT NULL,
    periodo INTEGER,
    modalidade VARCHAR(255),
    cod_disciplina VARCHAR(255) UNIQUE,
    cor VARCHAR(255),
    id_curso BIGINT NOT NULL REFERENCES curso(id_curso),
    id_tipo_sala BIGINT NOT NULL REFERENCES tipo_sala(id_tipo_sala),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO')),
    tipo_usuario VARCHAR(20) CHECK (tipo_usuario IN ('ADMINISTRADOR', 'COORDENADOR')),
    id_curso BIGINT REFERENCES curso(id_curso),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE turma (
    id_turma BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    periodo INTEGER NOT NULL,
    ano INTEGER NOT NULL,
    numero_alunos INTEGER NOT NULL,
    id_curso BIGINT NOT NULL REFERENCES curso(id_curso),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_turma_curso_ano_periodo UNIQUE (id_curso, ano, periodo)
);

CREATE TABLE quadro_horario (
    id_quadro_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versao INTEGER NOT NULL,
    data_criacao TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO')),
    id_curso BIGINT NOT NULL REFERENCES curso(id_curso),
    id_periodo_atividade_quadro BIGINT NOT NULL REFERENCES periodo_atividade_quadro(id_periodo_atividade_quadro),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recurso (
    id_recurso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    id_tipo_recurso BIGINT NOT NULL REFERENCES tipo_recurso(id_tipo_recurso),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professor_disciplina (
    id_professor_disciplina BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_professor BIGINT NOT NULL REFERENCES professor(id_professor),
    id_disciplina BIGINT NOT NULL REFERENCES disciplina(id_disciplina)
);

CREATE TABLE disponibilidade_professor (
    id_disponibilidade_professor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_professor BIGINT NOT NULL REFERENCES professor(id_professor),
    id_bloco_horario BIGINT NOT NULL REFERENCES bloco_horario(id_bloco_horario),
    dia_semana VARCHAR(20),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recurso_sala (
    id_recurso_sala BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade INTEGER NOT NULL,
    id_recurso BIGINT NOT NULL REFERENCES recurso(id_recurso),
    id_sala BIGINT NOT NULL REFERENCES sala(id_sala),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alocacao (
    id_alocacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(20) CHECK (dia_semana IN ('SEGUNDA', 'TERÇA', 'QUARTA', 'QUINTA', 'SEXTA', 'SÁBADO', 'DOMINGO')),
    id_bloco_horario BIGINT NOT NULL REFERENCES bloco_horario(id_bloco_horario),
    id_disciplina BIGINT NOT NULL REFERENCES disciplina(id_disciplina),
    id_professor BIGINT NOT NULL REFERENCES professor(id_professor),
    id_quadro_horario BIGINT NOT NULL REFERENCES quadro_horario(id_quadro_horario),
    id_sala BIGINT NOT NULL REFERENCES sala(id_sala),
    id_turma BIGINT NOT NULL REFERENCES turma(id_turma),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE historico_versao_alocacao (
    id_historico_versao_alocacaoo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao DATE NOT NULL,
    campo_alterado VARCHAR(255) NOT NULL,
    justificativa VARCHAR(255) NOT NULL,
    valor_antigo VARCHAR(255),
    valor_novo VARCHAR(255) NOT NULL,
    id_alocacao BIGINT NOT NULL REFERENCES alocacao(id_alocacao),
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id_usuario BIGINT NOT NULL UNIQUE REFERENCES usuario(id_usuario)
);


create table password_reset_token (
    id_password_reset_token bigint generated by default as identity,
    id_usuario bigint not null,
    token_hash varchar(64) not null unique,
    expires_at timestamp(6) with time zone not null,
    used boolean not null default false,
    created_at timestamp(6) with time zone not null,
    used_at timestamp(6) with time zone,
    primary key (id_password_reset_token)
);

alter table if exists password_reset_token
    add constraint FK_password_reset_token_usuario
    foreign key (id_usuario) references usuario;

create index IX_password_reset_token_usuario_used
    on password_reset_token (id_usuario, used);