create table refresh_token (
    id bigint generated by default as identity primary key,
    id_usuario bigint not null unique,
    token varchar(255) not null unique,
    expiry_date timestamp(6) with time zone not null,
    constraint FK_refresh_token_usuario foreign key (id_usuario) references usuario
);